export const movieType = {
  GET_BANNER_START: "GET_BANNER_START",
  GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
  GET_BANNER_ERROR: "GET_BANNER_ERROR",

  GET_LIST_MOVIE_START: "GET_LIST_MOVIE_START",
  GET_LIST_MOVIE_SUCCESS: "GET_LIST_MOVIE_SUCCESS",
  GET_LIST_MOVIE_ERROR: "GET_LIST_MOVIE_ERROR",

  ADD_MOVIE_START: "ADD_MOVIE_START",
  ADD_MOVIE_SUCCESS: "ADD_MOVIE_SUCCESS",
  ADD_MOVIE_ERROR: "ADD_MOVIE_ERROR",

  GET_MOVIE_DETAIL_START: "GET_MOVIE_DETAIL_START",
  GET_MOVIE_DETAIL_SUCCESS: "GET_MOVIE_DETAIL_SUCCESS",
  GET_MOVIE_DETAIL_ERROR: "GET_MOVIE_DETAIL_ERROR",

  GET_INFO_SHOWTIME_MOVIEL_START: "GET_INFO_SHOWTIME_MOVIEL_START",
  GET_INFO_SHOWTIME_MOVIE_SUCCESS: "GET_INFO_SHOWTIME_MOVIE_SUCCESS",
  GET_INFO_SHOWTIME_MOVIE_ERROR: "GET_INFO_SHOWTIME_MOVIE_ERROR",

  DELETE_MOVIE_START: "DELETE_MOVIE_START",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
  DELETE_MOVIE_ERROR: "DELETE_MOVIE_ERROR",
};

export const authTypes = {
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  USER_LOGOUT: "USER_LOGOUT",

  GET_USER_PROFILE_START: "GET_USER_PROFILE_START",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

  GET_PROFILE_BY_TOKEN_START: "GET_PROFILE_BY_TOKEN_START",
  GET_PROFILE_BY_TOKEN_SUCCESS: "GET_PROFILE_BY_TOKEN_SUCCESS",
  GET_PROFILE_BY_TOKEN_ERROR: "GET_PROFILE_BY_TOKEN_ERROR",
};

export const userType = {
  CREAT_USER_START: "CREAT_USER_START",
  CREAT_USER_SUCCESS: "CREAT_USER_SUCCESS",
  CREAT_USER_FAILURE: "CREAT_USER_FAILURE",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  GET_ALL_USER_START: "GET_ALL_USER_START",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_ERROR: "GET_ALL_USER_ERROR",

  GET_TYPE_USER_START: "GET_TYPE_USER_START",
  GET_TYPE_USER_SUCCESS: "GET_TYPE_USER_SUCCESS",
  GET_TYPE_USER_ERROR: "GET_ATYPEUSER_ERROR",

  DELETE_USER: " DELETE_USER",
};

export const ticketType = {
  CREATE_TICKET_START: "CREATE_TICKET_START",
  CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
  CREATE_TICKET_ERROR: "CREATE_TICKET_ERROR",

  GET_TICKET_ROOM_INFO_START: "GET_TICKET_ROOM_INFO_START",
  GET_TICKET_ROOM_INFO_SUCCESS: "GET_TICKET_ROOM_INFO_SUCCESS",
  GET_TICKET_ROOM_INFO_ERROR: "GET_TICKET_ROOM_INFO_ERROR",

  CREATE_CALENDAR_MOVIE_START: "CREATE_CALENDAR_MOVIE_START",
  CREATE_CALENDAR_MOVIE_SUCCESS: "CREATE_CALENDAR_MOVIE_SUCCESS",
  CREATE_CALENDAR_MOVIE_ERROR: "CREATE_CALENDAR_MOVIE_ERROR",

  CHON_GHE: "CHON_GHE",
  

  PAY_TICKET_START: "PAY_TICKET_START",
  PAY_TICKET_SUCCESS: "PAY_TICKET_SUCCESS",
  PAY_TICKET_ERROR: "PAY_TICKET_ERROR",

  RESET_GHE_DANG_CHON: "RESET_GHE_DANG_CHON",
};

export const theaterType = {
  GET_INFOR_MOVIE_THEATER_START: "GET_INFOR_MOVIE_THEATER_START",
  GET_INFOR_MOVIE_THEATER_SUCCESS: "GET_INFOR_MOVIE_THEATER_SUCCESS",
  GET_INFOR_MOVIE_THEATER_ERROR: "GET_INFOR_MOVIE_THEATER_ERROR",

  GET_CLUSTER_THEATER_START: "GET_CLUSTER_THEATER_START",
  GET_CLUSTER_THEATER_SUCCESS: "GET_CLUSTER_THEATER_SUCCESS",
  GET_CLUSTER_THEATER_ERROR: "GET_CLUSTER_THEATER_ERROR",

  GET_THEATER_SYSTEM_SHOWTIME_INFOR_START:
    "GET_THEATER_SYSTEM_SHOWTIME_INFOR_START",
  GET_THEATER_SYSTEM_SHOWTIME_INFOR_SUCCESS:
    "GET_THEATER_SYSTEM_SHOWTIME_INFOR_SUCCESS",
  GET_THEATER_SYSTEM_SHOWTIME_INFOR_ERROR:
    "GET_THEATER_SYSTEM_SHOWTIME_INFOR_ERROR",

  GET_INFOR_SHOWTIME_MOVIE_START: "GET_INFOR_SHOWTIME_MOVIE_START",
  GET_INFOR_SHOWTIME_MOVIE_SUCCESS: "GET_INFOR_SHOWTIME_MOVIE_SUCCESS",
  GET_INFOR_SHOWTIME_MOVIE_ERROR: "GET_INFOR_SHOWTIME_MOVIE_ERROR",
};

export const modalAntdType = {
  OPEN_MODAL_ANTD: "OPEN_MODAL_ANTD",
  CLOSE_MODAL_ANTD: "CLOSE_MODAL_ANTD",
  HANDLE_OK_MODAL_ANTD_WITH_LOADING: "HANDLE_OK_MODAL_ANTD_WITH_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  DISPLAY_LOADING: "DISPLAY_LOADING",
  HANDLE_OK_MODAL_ANTD_NO_LOADING: "HANDLE_OK_MODAL_ANTD_NO_LOADING",
  CANCEL_MODAL_ANTD: "CANCEL_MODAL_ANTD",
  CHANGE_CONTENT_MODAL_ANTD: "CHANGE_CONTENT_MODAL_ANTD",
};


export const drawerAntdType = {
  OPEN_DRAWER_ANTD: "OPEN_DRAWER_ANTD",
  CLOSE_DRAWER_ANTD: "CLOSE_DRAWER_ANTD",
}